spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration-api
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8180
